name: CAL
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - cffi=1.12.3=py36h2e261b9_0
  - cudatoolkit=10.0.130=0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.3=199
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.3=199
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy-base=1.16.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1b=h7b6447c_1
  - pip=19.1.1=py36_0
  - pycparser=2.19=py36_0
  - python=3.6.8=h0371630_0
  - pytorch=1.1.0=py3.6_cuda10.0.130_cudnn7.5.1_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py36_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - attrs==19.1.0
    - backcall==0.1.0
    - bcolz==1.2.1
    - bleach==3.1.0
    - cycler==0.10.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - imageio==2.5.0
    - imgaug==0.2.9
    - ipdb==0.12
    - ipykernel==5.1.1
    - ipython==7.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jinja2==2.10.1
    - joblib==0.13.2
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.0
    - mistune==0.8.4
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - networkx==2.3
    - notebook==5.7.8
    - numpy==1.16.4
    - opencv-python==4.1.0.25
    - pandas==0.24.2
    - pandocfilters==1.4.2
    - parso==0.4.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==6.0.0
    - prometheus-client==0.6.0
    - prompt-toolkit==2.0.9
    - protobuf==3.8.0
    - ptyprocess==0.6.0
    - pygame==1.9.6
    - pygments==2.4.2
    - pyparsing==2.4.0
    - pyrsistent==0.15.2
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pywavelets==1.0.3
    - pyzmq==18.0.1
    - qtconsole==4.5.1
    - scikit-image==0.15.0
    - scikit-learn==0.21.2
    - scipy==1.1.0
    - send2trash==1.5.0
    - shapely==1.6.4.post2
    - six==1.12.0
    - terminado==0.8.2
    - testpath==0.4.2
    - torch==1.1.0
    - torchvision==0.2.2.post3
    - tornado==6.0.2
    - tqdm==4.32.1
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2
prefix: /home/rsi/anaconda3/envs/CAL

